// app/custody/mock/fixtures.ts
// The canonical MOCK PARTIES + tenant records for the designer preview, plus the
// fixture-file types.
//
// There is NO captured registry: fixtures are generated by replaying close-wallets.ts's
// command shapes (Task 4). So party ids are derived deterministically here and imported
// by BOTH the tenant records and the fixture generator — a fixture contract and the
// tenant that should see it reference the identical string by construction.
//
// Sound because tenants.ts:38 copies `party` verbatim and derives `key` from `mnemonic`
// SEPARATELY — nothing validates they correspond and the mock signer never verifies a
// signature. The party string is authoritative; the key only exists to synthesize a
// real-shaped fingerprint for the audit UI.
// The `.js` suffix is REQUIRED — see the note in mock/store.ts.
import { sha256 } from '@noble/hashes/sha2.js';
import { bytesToHex } from '@noble/hashes/utils.js';
import { keyFromMnemonic } from '../../ledger-client/src/ed25519';
import type { TenantRecord } from '../tenants';
import type { AuditEntry } from '../app';
import type { SeedContract } from './store';

export type AcsFixture = SeedContract[];
export type AuditFixture = AuditEntry[];
export type UpdatesFixture = Record<string, unknown>;

/** The six custody roles, in the prod order. */
export const ROLES = ['gp', 'buyer', 'lpExiting', 'lpRolling', 'lpac', 'valuer'] as const;
export type Role = (typeof ROLES)[number];

/** Custodian display names — must match prod's story (provision.ts ROLES). */
const CUSTODIAN: Record<Role, string> = {
  gp: 'Fireblocks — GP Treasury',
  buyer: 'Copper — Northbeam Secondaries',
  lpExiting: 'Northgate Trust — Calder Family Office',
  lpRolling: 'BNY Digital — Hawthorn Pension',
  lpac: 'State Street Digital — LPAC',
  valuer: 'Kroll Valuation Services',
};

/**
 * BIP-39 test vectors — VALID mnemonics, PUBLIC, worthless. One per role, so each tenant
 * gets a distinct key (hence a distinct fingerprint and party id). These control nothing.
 */
const MNEMONICS: Record<Role, string> = {
  gp: 'abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about',
  buyer: 'legal winner thank year wave sausage worth useful legal winner thank yellow',
  lpExiting: 'letter advice cage absurd amount doctor acoustic avoid letter advice cage above',
  lpRolling: 'all hour make first leader extend hole alien behind guard gospel lava',
  lpac: 'vessel ladder alter error federal sibling chat ability sun glass valve picture',
  valuer: 'gravity machine north sort system female filter attitude volume fold club stay feature office ecology',
};

/** Documented preview credentials — the designer cannot guess these. */
export const DEMO_PASSWORD = (role: string): string => `${role}-demo`;

/**
 * Canton computes fingerprints server-side (wallet.ts:115 reads
 * topo.publicKeyFingerprint), so there is no offline "real" path. Synthesize one in
 * Canton's shape — '1220' + sha256 hex — real-SHAPED, wrong-valued. Shown in the audit
 * trail; a designer will size a column to it.
 */
export const mockFingerprint = (rawPub: Uint8Array): string => `1220${bytesToHex(sha256(rawPub))}`;

const roleFingerprint = (role: Role): string => mockFingerprint(keyFromMnemonic(MNEMONICS[role]).rawPub);

/**
 * The canonical role → party id map. party = continuum-<role>-mock::<fingerprint>,
 * mirroring how a real onboarded party id embeds its key fingerprint after the `::`.
 * THE single source of truth for party identity across tenants and fixtures.
 */
export const MOCK_PARTIES: Record<Role, string> = Object.fromEntries(
  ROLES.map((role) => [role, `continuum-${role}-mock::${roleFingerprint(role)}`]),
) as Record<Role, string>;

/** Build the six mock tenant records from the canonical constants. */
export function mockTenantRecords(): TenantRecord[] {
  return ROLES.map((role) => ({
    tenant: role,
    custodianName: CUSTODIAN[role],
    role,
    party: MOCK_PARTIES[role],
    mnemonic: MNEMONICS[role],
    fingerprint: roleFingerprint(role),
    username: role,
    password: DEMO_PASSWORD(role),
  }));
}
