// app/custody/docs/gen-manifest.ts
// Computes the REAL sha256 of the exact served document bytes and emits:
//   - manifest.json  (public metadata + hashes, served at GET /docs/manifest)
//   - hashes.ts      (typed constants the headless flow anchors on-chain)
// The hash is taken over the file bytes on disk, which are the SAME bytes /docs/:name
// serves — so /verify recomputes an identical digest. Regenerate after editing any doc:
//   cd app && npx tsx custody/docs/gen-manifest.ts
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const DIR = dirname(fileURLToPath(import.meta.url));
const sha256 = (name: string) =>
  createHash('sha256').update(readFileSync(resolve(DIR, name))).digest('hex');

type Entry = {
  name: string;
  file: string;
  title: string;
  group: 'Deal Formation' | 'Process Certifications' | 'Settlement';
  signer: string;
  date: string;
  templateSuffix: string;
};

const DOCS: Entry[] = [
  {
    name: 'valuation-report',
    file: 'valuation-report.html',
    title: 'Independent Valuation — Project Continuum CV I, L.P.',
    group: 'Deal Formation',
    signer: 'Kroll Valuation Services',
    date: '2026-06-30',
    templateSuffix: 'Continuum.Valuation:ValuationReport',
  },
  {
    name: 'fairness-opinion',
    file: 'fairness-opinion.html',
    title: 'Fairness Opinion — Project Continuum CV I, L.P.',
    group: 'Deal Formation',
    signer: 'State Street Digital — LPAC',
    date: '2026-06-30',
    templateSuffix: 'Continuum.Valuation:FairnessOpinion',
  },
  {
    name: 'purchase-agreement',
    file: 'purchase-agreement.html',
    title: 'Purchase & Sale Agreement — Project Continuum CV I, L.P.',
    group: 'Settlement',
    signer: 'Fireblocks — GP Treasury',
    date: '2026-06-30',
    templateSuffix: 'Continuum.Issuance:PurchaseAgreement',
  },
];

const manifest = DOCS.map((d) => ({
  name: d.name,
  file: d.file,
  title: d.title,
  group: d.group,
  signer: d.signer,
  date: d.date,
  sha256: sha256(d.file),
  templateSuffix: d.templateSuffix,
  contentType: 'text/html; charset=utf-8',
}));

writeFileSync(resolve(DIR, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');

const byName = Object.fromEntries(manifest.map((m) => [m.name, m.sha256]));
const hashesTs = `// app/custody/docs/hashes.ts — GENERATED by gen-manifest.ts. Do not edit by hand.
// The REAL sha256 (hex) of the exact bytes served at GET /docs/:name. These become the
// on-chain \`contentHash\` (Daml BytesHex) when the flow anchors each document contract.
export const VALUATION_SHA256 = '${byName['valuation-report']}';
export const FAIRNESS_SHA256 = '${byName['fairness-opinion']}';
export const PSA_SHA256 = '${byName['purchase-agreement']}';

/** name → sha256, for the /verify endpoint and manifest consumers. */
export const DOC_SHA256: Record<string, string> = {
  'valuation-report': VALUATION_SHA256,
  'fairness-opinion': FAIRNESS_SHA256,
  'purchase-agreement': PSA_SHA256,
};
`;
writeFileSync(resolve(DIR, 'hashes.ts'), hashesTs);

console.log('wrote manifest.json + hashes.ts:');
for (const m of manifest) console.log(`  ${m.name.padEnd(20)} ${m.sha256}`);
