// app/custody/docs/hashes.ts — GENERATED by gen-manifest.ts. Do not edit by hand.
// The REAL sha256 (hex) of the exact bytes served at GET /docs/:name. These become the
// on-chain `contentHash` (Daml BytesHex) when the flow anchors each document contract.
export const VALUATION_SHA256 = 'fb79d03a6e7b739acd70f090b10aabdf39771c63292e92bb3fc59162096b0440';
export const FAIRNESS_SHA256 = '1a667a08add149437a5ab6eafce36b685b84c2761224c850b4ef07d34c469ed3';
export const PSA_SHA256 = '9f1efbb05dc08016c40d3ed860a008253df94567f9073b09a34ccf61cd4d5660';

/** name → sha256, for the /verify endpoint and manifest consumers. */
export const DOC_SHA256: Record<string, string> = {
  'valuation-report': VALUATION_SHA256,
  'fairness-opinion': FAIRNESS_SHA256,
  'purchase-agreement': PSA_SHA256,
};
