// app/custody/docs/hashes.ts — GENERATED by gen-manifest.ts. Do not edit by hand.
// The REAL sha256 (hex) of the exact bytes served at GET /docs/:name. These become the
// on-chain `contentHash` (Daml BytesHex) when the flow anchors each document contract.
export const VALUATION_SHA256 = 'ab5a539d8b780626370a095f2eb5f1c245abe242a772462e644706b73607de09';
export const FAIRNESS_SHA256 = '9a3ca06cd71f318717500357625d414f2d052611244b2826f0c1ce506dd42f8c';
export const PSA_SHA256 = '83edf119cf090fe56d1a69507018dae2108fbdde88f9ba7c596ae30fbf5f185e';

/** name → sha256, for the /verify endpoint and manifest consumers. */
export const DOC_SHA256: Record<string, string> = {
  'valuation-report': VALUATION_SHA256,
  'fairness-opinion': FAIRNESS_SHA256,
  'purchase-agreement': PSA_SHA256,
};
